//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazaMvcProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refrigator
    {
        public int refId { get; set; }
        public string refColor { get; set; }
        public bool freezerPlace { get; set; }
        public string soundLevel { get; set; }
        public string energyClass { get; set; }
        public decimal refPrice { get; set; }
        public int dealerId { get; set; }
        public int customerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Dealer Dealer { get; set; }
    }
}
