//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazaMvcProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Television
    {
        public int tvId { get; set; }
        public string resolution { get; set; }
        public Nullable<int> screenSize { get; set; }
        public bool androidSystem { get; set; }
        public string energyClass { get; set; }
        public string color { get; set; }
        public decimal tvPrice { get; set; }
        public int dealerId { get; set; }
        public int customerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Dealer Dealer { get; set; }
    }
}
