//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazaMvcProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WashingMachine
    {
        public int washId { get; set; }
        public string capacity { get; set; }
        public string spinCycle { get; set; }
        public string machineColor { get; set; }
        public string energiesClass { get; set; }
        public decimal washPrice { get; set; }
        public int dealerId { get; set; }
        public int customerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Dealer Dealer { get; set; }
    }
}
